site:
  title: ProjectItSite
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://joswarmer.github.io/ProjectIt
  start_page: projectit-component::README.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: projectit-doc/component-main
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/v205/ui-bundle.zip
#    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./projectit-templates/projectit
#  supplemental_files: ./projectit-templates/antora-default
output:
  dir: ../docs

